"""Readable numerical ledger generated from the completed, audited study."""
from pathlib import Path
from temporal_evidence.io import read_json
from temporal_evidence.analysis.publication import SOURCES, METHODS, number, percent, fraction


def generate():
    publication = read_json('artifacts/analysis/publication.json')
    assert publication['complete'] and publication['integrity']['passed']
    study = read_json('artifacts/analysis/minimum_v1/summary.json')
    systems = read_json('artifacts/analysis/streaming_v1/summary.json')
    lines = ['# Measured study results', '',
             'Generated by `PYTHONPATH=src .venv/bin/python -m temporal_evidence.analysis.measurements`.', '',
             f"Protocol: `{publication['protocol_hash']}`. All 3,600 planned cases are accounted for.", '',
             'Rates below are percentages; undefined conditional rates are shown as `--`. '
             'Pointwise intervals use 2,000 subject-cluster resamples. Each source has ten held-out subjects.', '']

    def table(title, header, rows):
        lines.extend(['## '+title, '', '| '+' | '.join(header)+' |', '| '+' | '.join(['---']*len(header))+' |'])
        lines.extend('| '+' | '.join(str(value) for value in row)+' |' for row in rows)
        lines.append('')

    ordered = [next(r for r in study['summary'] if (r['dataset'],r['method']) == (source,method))
               for source in SOURCES for method in METHODS]
    table('Fresh displayed answers', ['Source','Method','Cases','Case error %','Claim error %','Fact recall %','Useful coverage %','Claims'],
          [[SOURCES[r['dataset']],r['method'],r['cases'],percent(r['case_error']['value']),percent(r['claim_error']['value']),
            percent(r['fact_recall']['value']),percent(r['useful_coverage']['value']),r['claim_error']['denominator']] for r in ordered])
    table('Persistent displays', ['Source','Method','Corrected/required','Completeness %','Residual','Collateral/unaffected'],
          [[SOURCES[r['dataset']],r['method'],fraction(r['correction_completeness']),percent(r['correction_completeness']['value']),
            r['residual_incorrect']['numerator'],fraction(r['collateral_revision'])] for r in ordered])
    table('Descriptive parent-only changes', ['Source','Method','Required under declared dependencies','Withdrawn','Retained'],
          [[SOURCES[r['dataset']],r['method'],r['required'],r['withdrawn'],r['retained']] for r in publication['dependency_only_changes']])
    lines.extend(['These claim-checkpoint counts isolate cases whose sole later exact-check error is a parent dependency. '
                  'The declared link is treated as a prerequisite; its semantic necessity is not independently established. '
                  'This descriptive breakdown leaves the frozen correction metrics unchanged.', ''])
    table('Paired differences', ['Source','Contrast','Outcome','Subjects/episodes','Difference (pp)','Pointwise 95% interval (pp)','Principal'],
          [[SOURCES[r['dataset']],r['left']+' − '+r['right'],r['metric'],f"{r['subjects']}/{r['eligible_episodes']}",
            number(None if r['difference'] is None else 100*r['difference']),
            '--' if r['ci95'] is None else '['+', '.join(number(100*v) for v in r['ci95'])+']',r['principal']] for r in study['contrasts']])
    table('Open-loop systems', ['Events/s','Method','Flag p50/p95 ms','Replacement p50/p95 s','Flag misses','Replacement misses','Peak event/answer queue','Achieved events/s'],
          [[r['offered_events_per_second'],r['method'],
            '/'.join(number(1000*r['event_to_flag'][q]) for q in ('p50','p95')),
            '/'.join(number(r['event_to_generated_repair'][q]) for q in ('p50','p95')),
            f"{r['flag_misses']}/{r['flag_denominator']}", f"{r['repair_misses']}/{r['repair_denominator']}",
            f"{r['peak_event_backlog']}/{r['peak_pending_explanations']}",number(r['achieved_events_per_second_including_drain'],2)] for r in systems['cells']])
    lines.extend(['Flag and replacement targets are one and five seconds, respectively. '
                  'Replacement adequacy in the frozen benchmark refers to the input snapshot. '
                  'Each cell schedules arrivals for 60 seconds and then drains.', ''])
    table('Descriptive completion-time adequacy', ['Events/s','Method','Explanations','Input adequate','Completion adequate','Adequate then stale'],
          [[r['offered_events_per_second'],r['method'],r['completion_audited'],r['adequate_at_request'],
            r['adequate_at_completion'],r['adequate_then_stale']] for r in systems['cells']])
    table('Generation failures and use', ['Source','Method','Failed','Truncated initially','Repair calls','Abstained %','Valid references %'],
          [[SOURCES[r['dataset']],r['method'],r['failed']['numerator'],r['initial_truncation']['numerator'],r['repair_calls']['numerator'],
            percent(r['abstained']['value']),percent(r['reference_validity']['value'])] for r in ordered])
    table('Logged request error categories', ['Source','Method','Phase','Category','Calls'],
          [[SOURCES[r['dataset']],r['method'],r['phase'],r['error_type'],r['count']] for r in publication['request_error_types']])
    lines.extend([f"Initial request/format failures: {publication['macros']['TotalInitialErrors']}; "
                  f"client timeout attempts across initial and repair phases: {publication['macros']['ClientTimeouts']}. "
                  'Truncation and request/format failure counts can overlap.', ''])
    table('Measured workload costs', ['Workload','Requests','Input tokens','Output tokens','Wall minutes'],
          [[r['name'],f"{r['calls']:,}",f"{r['input_tokens']:,}",f"{r['output_tokens']:,}",number(r['seconds']/60)] for r in publication['workloads']])
    lines.extend(['These are observed GPU-backed workload wall times, including host processing. '
                  'They exclude downloads, initial server compilation, and unlogged gaps. '
                  'They are neither CUDA kernel time nor total billable pod time. No account price was supplied.', ''])
    table('Automated auxiliary audit', ['Source','Method','Sampled','Parsed','Flagged','Exact supported','Disagreements'],
          [[SOURCES[r['dataset']],r['method'],r['sampled'],r['parsed'],r['flagged'],r['exact_all_claims_supported'],r['disagreements']]
           for r in publication['audit_details']['strata']])
    audit = publication['automated_audit']
    lines.extend([f"The separate CUDA verifier gives the expected result on {audit['calibration_correct']}/4 diagnostic examples. "
                  'It is not a human gold standard. Selection is conditional on nonempty checkpoint-2 answers; '
                  'the primary coverage metrics retain empty answers. Full disagreements are in `minimum_v1/audit_details.json`.', '',
                  '## Provenance and limitations', '',
                  'All rows derive from `publication.json`, `minimum_v1/summary.json`, and `streaming_v1/summary.json` in this directory. '
                  'Database counts and resource traces are linked by the publication manifest. '
                  'Physiological source faithfulness is not physiological accuracy. '
                  'The numerical claim contract, small participant cohorts, one generation seed, and single load-test cell per rate limit generalization.', ''])
    Path('artifacts/analysis/measurements.md').write_text('\n'.join(lines))


if __name__ == '__main__':
    generate()
